include("shared.lua")

net.Receive("WorkerMenu", function()
    local ent = net.ReadEntity()
    local frame = vgui.Create("DFrame")
    frame:SetSize(320, 200)
    frame:SetTitle("Worker Settings")
    frame:Center()
    frame:MakePopup()
    frame.Paint = function(self, w, h)
        draw.RoundedBox(0, 0, 0, w, h, Color(25, 25, 25, 240))
        draw.RoundedBox(0, 0, 0, w, 30, Color(150, 0, 0, 255))
    end

    local label = vgui.Create("DLabel", frame)
    label:SetText("Set disposal mode for the worker:")
    label:SetTextColor(Color(255, 255, 255))
    label:SetPos(20, 40)
    label:SizeToContents()

    local legalBtn = vgui.Create("DButton", frame)
    legalBtn:SetText("Legal Disposal")
    legalBtn:SetPos(50, 80)
    legalBtn:SetSize(220, 30)
    legalBtn.DoClick = function()
        net.Start("SetWorkerDisposal")
        net.WriteEntity(ent)
        net.WriteBool(true)
        net.SendToServer()
        frame:Close()
    end
    legalBtn.Paint = function(self, w, h)
        draw.RoundedBox(0, 0, 0, w, h, Color(100, 0, 0, 200))
    end

    local illegalBtn = vgui.Create("DButton", frame)
    illegalBtn:SetText("Illegal Disposal")
    illegalBtn:SetPos(50, 120)
    illegalBtn:SetSize(220, 30)
    illegalBtn.DoClick = function()
        net.Start("SetWorkerDisposal")
        net.WriteEntity(ent)
        net.WriteBool(false)
        net.SendToServer()
        frame:Close()
    end
    illegalBtn.Paint = function(self, w, h)
        draw.RoundedBox(0, 0, 0, w, h, Color(100, 0, 0, 200))
    end
end)